/*
  This code will add the Unicorn and the #tamingunicorns hashtag
  to your conference badge.
  This will not overwrite your name!
  If you are not happy with your badge upgrade, remove the badge battery.
  This resets the badge.

  for the workshop - this is the link you are looking for http://bit.ly/2yCS3uQ

  Believe in unicorns!
*/

var hashtag = {
  width : 128, height : 60, bpp : 1,
  transparent : 0,
  buffer : E.toArrayBuffer(atob("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAAAAAwGAAAAAAAAAAAAAAAAAAAOD3AAAAAAAAAAAAAAAAAABz/wAAAAAAAAAAAAAAAAAgPB+AAAAAAAAAAAAAAAAAwPQ/gAAAAAAAAAAAAAAAAMH4f+AAAAAAAAAAAAAAAAHP8f/wAAAgAAAAAAAAAAAA/+P/OAAAYAAAAAAAAAAAAP+D/jgAAOAAAAAAAAAAAAB/B/48AADgAAAAAAAAAAAAIAffDAAA4AAAAAAAAAAAAAAP/y4AAPAAAAAAAAAAAAAAHj8OAADwAAAAAAAAAAAAAH9/DgAA+AAAAAAAAAAAAAB9/48AAegAAAAAAAAAAAAA//+PEAHoAAAAAAAAAAAAAf//j/AD6AAAAAAAAAAAAAP//4fwA/AAAAAAAAAAAAAP///H8AfkAAAAAAAAAAAAH///x+AH8AAAAAAAAAAAAD///+IAD/AAAAAAAAAAAAA////gAA/gAAAAAAAAAAAAb///8AAP8AAAAAAAAAAAAH////gAD+AAAAAAAAAAAAB////8P//gAAAAAAAAAAAAf///////wAAAAAAAAAAAAD///////8AAAAAAAAAAAAA////////AAAAAAAAAAAAAH//H////4AAAAAAAAAAAAA//A////+AAAAAAAAAAAAAH/AP////gAAAAAAAAAAAAA/AB////4AAAAAAAAAAAAAAAAf///+AAAAAAAAAAAAAAAAf////gAAAAAAAAAAAAAAAN////4AAAAAAAAAAAAAAAPv///8AAAAAAAAAAAAAAAf7////AAAAAAAAAAAAAAAf/////4AAAAAAAAAAAAAA//f////gAAAAAAAAAAAAAH/38AH/8AAAAAAAAAAAAAA///AAD/wAAAAAAAAAAAAAH8/wAPf+AAAAAAAAAAAAAA+f4AB7/4AAAAAAAAAAAAADP+AAff4AAAAAAAAAAAAAAD/gAD/8AAAAAAAAAAAAAAB/wAAf8AAAAAAAAAAAAAAAP8AAHwAAAAAAAAAAAAAAAB+AAAAAAAAAAAAAAAAAAAAHgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"))
};

var uniCorn = {
  width : 76, height : 60, bpp : 1,
  transparent : 0,
  buffer : E.toArrayBuffer(atob("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAQAAAAAAAAAAABgAAAAAAAAAAADAYAAAAAAAAAAOD3AAAAAAAAAAc/8AAAAAAAACA8H4AAAAAAAAwPQ/gAAAAAAADB+H/gAAAAAAAc/x//AAACAAAA/+P/OAAAYAAAD/g/44AADgAAAH8H/jwAAOAAAAIAffDAAA4AAAAAD/8uAADwAAAAAePw4AAPAAAAAH9/DgAA+AAAAAff+PAAHoAAAAD//48QAegAAAAf//j/AD6AAAAD//+H8APwAAAA///8fwB+QAAAH///x+AH8AAAA////iAA/wAAAD///+AAD+AAAAb///8AAP8AAAB////4AA/gAAAH////w//+AAAAf///////wAAAA////////AAAAD///////8AAAAH//H////4AAAAP/wP////gAAAAf8A////+AAAAA/AB////4AAAAAAAH////gAAAAAAB////+AAAAAAAN////4AAAAAAD7////AAAAAAB/v///8AAAAAAf/////4AAAAAP/3////4AAAAAf/fwAf/wAAAAA///AAD/wAAAAB/P8AD3/gAAAAD5/gAHv/gAAAADP+AAff4AAAAAA/4AA//AAAAAAH/AAB/wAAAAAAP8AAHwAAAAAAAfgAAAAAAAAAAAeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"))
};

Badge.badgeImages.push(hashtag);
Badge.badgeImages.push(uniCorn);


// This bit will allow you to NFC directly to the hashtag with your Android phone
// Our collective dream is to have a mildly trending hastag.
// Please help us make it a reality.

Badge.URL="https://twitter.com/hashtag/TamingUnicorns?src=hash";
